title: Nicholas Ramirez
#logo:(![B3AFD36D-7B40-4BD1-8985-7565616B3ACA.JPEG](assests/B3AFD36D-7B40-4BD1-8985-7565616B3ACA.JPEG))
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal
